spring:
  application:
    name: backend


  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}


# Tämä on se update
  #jpa:
    #hibernate:
      #ddl-auto: update

# Ja tämä on se, joka käynnistää databasen joka kerta alusta
  sql:
  init:
    mode: always



  cloud:
    aws:
      secretsmanager:
        region: eu-north-1

jwt:
  private.key: classpath:./jwt-keys/app.key
  public.key: classpath:./jwt-keys/app.pub


logging:
  level:
    org.springframework:
      security: trace


management:
  endpoints:
    web:
      exposure:
        include: health, info



